### ISSUE TITLE
fix: absurdly long build times

### ISSUE THREAD

**Issue by xynydev** [blue-build/github-action#16]
My build times before using BlueBuild cli: ~6min   
My build times after using BlueBuild cli: ~6min   
My build times after the switch to running the build in podman: ~12-16min

A good chunk of this time is spent on removing unwanted software. Maybe making this step optional, controlled by an input, would be beneficial.

Some time is spent installing podman and pulling the container, but this doesn't seem excessive when looking back at the logs. Maybe that's just what pushed my buildd over the 10 minutes.

**Comment by gerblesh** [comment]
running buildah in podman definitely slows things down. I'd take a look at https://github.com/blue-build/github-action/commit/7145d29c8e5d9a0e7a8d405125de02aebd269e3c though, you can try out the current changes along with keyless signing using the `testing` branch

**Comment by xynydev** [comment]
I"ll add a toggle for turning the unwanted software removal on and off to see if that helps.

**Comment by xynydev** [comment]
I tried to re-implement the changes in the testing branch without changing the cli version in [`containerd-volume-mount`](https://github.com/blue-build/github-action/tree/containerd-volume-mount), but it didn't make the builds much faster (like 20 seconds, which is less than the standard deviation). I changed the cli version to basically mimic the `testing` branch and the fonts module issue came up again.

I think I figured out the reason: https://github.com/blue-build/cli/commit/411e782dc84800584d10225728495da1178aef8d
The fonts module uses ` | tr -d '\n'` to remove the newline. Disabling that would break the builds for legacy template users, though. One thing I don't understand is that if the var doesn't have a newline, how come trying to remove it breaks things. Maybe this issue happens earlier, when the array is being passed to the font download script... The fonts module is due a refactor anyways, so let me just make an issue for that...

**Comment by fiftydinar** [comment]
> I tried to re-implement the changes in the testing branch without changing the cli version in [`containerd-volume-mount`](https://github.com/blue-build/github-action/tree/containerd-volume-mount), but it didn't make the builds much faster (like 20 seconds, which is less than the standard deviation). I changed the cli version to basically mimic the `testing` branch and the fonts module issue came up again.
> 
> I think I figured out the reason: [blue-build/cli@411e782](https://github.com/blue-build/cli/commit/411e782dc84800584d10225728495da1178aef8d) The fonts module uses ` | tr -d '\n'` to remove the newline. Disabling that would break the builds for legacy template users, though. One thing I don't understand is that if the var doesn't have a newline, how come trying to remove it breaks things. Maybe this issue happens earlier, when the array is being passed to the font download script... The fonts module is due a refactor anyways, so let me just make an issue for that...

As a workaround, custom get_yaml_array function can be defined, to not break user experience

**Comment by xynydev** [comment]
Since the issue that the `testing` branch had is solved, I deleted my `containerd-volume-mount` branch and will update to the next cli release with a PR built on the testing branch. Then I'll delete the branch per #17. Feel free to come fight over there.

**Comment by xynydev** [comment]
Switching to `docker` for builds could be a solution, as there is an up-to-date ppa available: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository

This would need support in cli.

**Comment by tulilirockz** [comment]
worst case you guys can use the nix docker build to run those in github runners

**Comment by xynydev** [comment]
Latest release should've basically fixed this.
