### ISSUE TITLE
feat: add input to use nightly cli

### ISSUE THREAD

**Issue by xynydev** [blue-build/github-action#17]
Useful for testing and those who want to live on the edge.

**Comment by gerblesh** [comment]
already done in the `testing` branch:
https://github.com/blue-build/github-action/blob/testing/action.yml

**Comment by xynydev** [comment]
Ah, hmm. Seems that the branch exists so that it could be used for testing directly, but doesn't that make merging changes from there harder? I'd rather implement an input that allows the user of the action to use the nightly build of cli, which could be used with any feature development branch if needed.

This would also more closely follow with the leaner standard ["GitHub Flow"](https://docs.github.com/en/get-started/using-github/github-flow#following-github-flow) AKA [trunk-based development](https://trunkbaseddevelopment.com/), instead of the classic (but IMO a bit clunky) ["Git flow"](https://www.gitkraken.com/learn/git/git-flow).

**Comment by xynydev** [comment]
The testing branch somehow broke the `fonts` module(??) Subsequent builds on the main branch all worked.

https://github.com/xynydev/linuXYZ/actions/runs/8002429699/job/21856533903

**Comment by gmpinder** [comment]
> Ah, hmm. Seems that the branch exists so that it could be used for testing directly, but doesn't that make merging changes from there harder? I'd rather implement an input that allows the user of the action to use the nightly build of cli, which could be used with any feature development branch if needed.
> 
> This would also more closely follow with the leaner standard ["GitHub Flow"](https://docs.github.com/en/get-started/using-github/github-flow#following-github-flow) AKA [trunk-based development](https://trunkbaseddevelopment.com/), instead of the classic (but IMO a bit clunky) ["Git flow"](https://www.gitkraken.com/learn/git/git-flow).
> 
> And currently the testing branch doesn't use the `-nightly` builds, just the main branch ones. I'm actually not sure what the difference is. cc: @gmpinder 

So `main` is whatever we have in the main branch. The `nightly` tag is the CLI complex with the `nightly` feature set which is like experimental features that aren't necessarily ready for the default feature set.

**Comment by gerblesh** [comment]
I think adding an input for nightly/testing would be dangerous because the build command could be required to change. IMO if you use a version locked github action, it should pull down a specific CLI version that works with the action. If one wants to use a main/nightly version, they can do so by specifying `testing` or `nightly-testing` as the version of the action to use

**Comment by xynydev** [comment]
Keep in mind that this testing input would be used for testing and users should not expect stability from it. Feature branches using a testing version would be used to test those features. I disagree with the use of an unified testing branch both for new features in the action and new features in cli due to points stated above. I don't think a flag allowing the change to a testing tag introduces any more instability, just changes the DX a bit, and allows for testing new cli versions without testing new action features.

For example, we don't currently know if the testing branch regression with the fonts module is due to changes in how cli is run or changes in cli itself.
