### ISSUE TITLE
Update maximize_build_space action to save more space (following [#1034](https://github.com/ublue-os/bluefin/pull/1034))

### ISSUE THREAD

**Issue by ispanos** [blue-build/github-action#33]
I'm trying to catch up on the latest changes in Bluefin and I saw a [comment](https://github.com/ublue-os/bluefin/pull/1034/files#r1543264795) which says that  [ublue-os/remove-unwanted-software](https://github.com/blue-build/github-action/blob/b436eae266ae1486f3263bcf2836d5eeac807eee/action.yml#L60C13-L60C47) is out of date. I checked the commit history and I think that it is still the case.

Bluefin uses [jlumbroso/free-disk-space@v1.3.1](https://github.com/ublue-os/bluefin/blob/c843cca3c7d157b5128b1446bc77cd05e833edef/.github/workflows/build_iso.yml#L50) now, which "can clear up to 31 GB of disk space in about 3 minutes" compared to the "19GB" of ublue-os/remove-unwanted-software (potentially less since "its not up to date"). Could you update the action called when `maximize_build_space` is set to true? Would you like me to open a PR?

Also, is it possible for me to use the blue-build action with an extra "space-maximizing" action in my `build.yml`?

Thank you.

**Comment by xynydev** [comment]
Sure. Want do do a PR? I can maybe do this in some 24 hours too...
