### ISSUE TITLE
refactor: choosing the default compromise

### ISSUE THREAD

**Issue by xynydev** [blue-build/github-action#34]
Squashing builds, or caching builds?

@gmpinder

**Comment by gmpinder** [comment]
I'm personally of the opinion that we should prefer caching builds. There are some things we still need to handle like https://github.com/blue-build/cli/issues/156 and https://github.com/blue-build/cli/issues/138 to truly allow the choice. The latter should give us much better caching abilities. I also have a suspicion that this would help reduce update sizes (still needs to be tested out) by only making new layers as they are actually needed.

**Comment by xynydev** [comment]
If we can keep the image size good, yeah, probably faster builds is the goal. One thing to consider, is that most users' GitHub build time is free and expendable, while their bandwidth might not be.

**Comment by gmpinder** [comment]
> If we can keep the image size good, yeah, probably faster builds is the goal. One thing to consider, is that most users' GitHub build time is free and expendable, while their bandwidth might not be.

I totally get that, but if their base image gets an update, they'll have to download all those layers as well as the layer(s) created by `bluebuild` anyways regardless of if it's squashed. With the cache option though, rapid development to make tweaks will save bandwidth immensely especially with my findings in https://github.com/blue-build/cli/pull/157.
