### ISSUE TITLE
fix: build failing

### ISSUE THREAD

**Issue by xynydev** [blue-build/github-action#5]
Eventhough `latest-installer` is now published, the builds still fail for me and I have no idea why. I don't really wanna go back to cargo installs, and running reusable composite actions inside containers isn't possible for some reason...
```
Cleaning up image
blue-build-installer
Untagged: ghcr.io/blue-build/cli:latest-installer
Deleted: 8772522991b671f563f80d5956db88e4362446cf6eff8284d81d1a64718d22b1
Failed to copy file, try:
	podman run --rm ghcr.io/blue-build/cli:latest-installer | sudo bash
Error: Process completed with exit code 1.
```

**Comment by gmpinder** [comment]
I can take a look later today

**Comment by gmpinder** [comment]
Alright my builds are working with this action now https://github.com/gmpinder/wunker-os/actions/runs/7673676059/job/20916782178

**Comment by xynydev** [comment]
Ok, the action still uses `| sudo bash`, but the build _is_ actually working. I'll close this then, and remove the sudo just to keep this in-line with the "suggested" method in the cli README.
