### ISSUE TITLE
Error: Could not find the file /out/bluebuild in container blue-build-installer

### ISSUE THREAD

**Issue by ragibkl** [blue-build/github-action#52]
I keep getting the following error in my builds. I have no idea what's going on.
example failed job: https://github.com/ragibkl/fedora-bluebuild/actions/runs/9438214317/job/25994972439

```
Status: Downloaded newer image for ghcr.io/blue-build/cli:main-installer
9a35b2bf7dbdbb0b5cc28e4acf578a95693c281cc85d5c84375fea398d7e1676
Error response from daemon: Could not find the file /out/bluebuild in container blue-build-installer
Error: Process completed with exit code 1.
```

**Comment by ragibkl** [comment]
Looks like I was still using: `use_unstable_cli: true`. The features that I was using no longer needed this flag. I turned this off and builds are green again!

Closing this issue.

**Comment by gmpinder** [comment]
This is still an issue that I should look into. The binary is supposed to be there

**Comment by gmpinder** [comment]
Ok I found the issue. I wasn't outputting the binary into the correct directory. https://github.com/blue-build/cli/commit/c12deec5894415ac6b8535af45ff3a532c1ba387
