### ISSUE TITLE
No labels are present on the image when building from the gh action

### ISSUE THREAD

**Issue by yacoob** [blue-build/github-action#64]
Example: 
- [image](https://github.com/yacoob/yaurora/pkgs/container/yaurora/303997395?tag=latest)
- [matching workflow run](https://github.com/yacoob/yaurora/actions/runs/11789338579/job/32837935816)
- [the workflow file](https://github.com/yacoob/yaurora/blob/main/.github/workflows/build.yaml)

If I `bluebuild generate` or `build` locally on my machine, the labels are present.

**Comment by xynydev** [comment]
Running `skopeo inspect docker://ghcr.io/yacoob/yaurora@sha256:52106740ca0714c1a26e8c3f0f350cc357f6016258be71f8bd404d60a990ae6a` (your linked image) gives these labels:

```json
 "Labels": {
        "containers.bootc": "1",
        "dev.hhd.rechunk.info": "[truncated]",
        "io.artifacthub.package.logo-url": "https://avatars.githubusercontent.com/u/120078124?s=200\u0026v=4",
        "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/blue-build/cli/main/README.md",
        "org.blue-build.build-id": "3bd426e6-689f-4d3c-9574-c58dd46ada89",
        "org.opencontainers.image.created": "2024-11-10T16:54:15.354Z",
        "org.opencontainers.image.description": "💙 ublue-os/aurora-dx the way I like it",
        "org.opencontainers.image.licenses": "Apache-2.0",
        "org.opencontainers.image.revision": "af758c029bf9d04ba4777a3da2db02013db937fc",
        "org.opencontainers.image.source": "https://github.com/yacoob/yaurora",
        "org.opencontainers.image.title": "yaurora",
        "org.opencontainers.image.url": "https://github.com/ublue-os/bluefin",
        "org.opencontainers.image.version": "40.20241109.0",
        "ostree.bootable": "true",
        "ostree.commit": "8d17d8ef4035bd13d57a258b2edf498b36d0760f1f1b87dfccc3f2592211cb49",
        "ostree.final-diffid": "sha256:12787d84fa137cd5649a9005efe98ec9d05ea46245fdc50aecb7dd007f2035b1",
        "ostree.linux": "6.11.3-200.fc40.x86_64"
    },
```

Probably just a GitHub UI issue then?

**Comment by yacoob** [comment]
Ha, that is weird. I've looked at other `ublue-os` images, and they're also labeled this way. I'd swear I've looked at the output of `skopeo inspect`, but clearly not closely enough.

Happy that there isn't a heisenbug here :) Will try to figure out why Github doesn't like these. I'll update this bug, if I find anything pertinent.

Thanks, and thanks for a sanity check here! :)
